### PR TITLE
Insert the coordinates of the origin

### PR DESCRIPTION
**Pull request by Rob-Lop**
Insert the real coordinates of the recalculated origin.

### CODE REVIEW

**Comment by liberostelios** [comment]
Thank you for your pull request. As far as I can see, this piece of work will only add a text object to the centre of the scene. I am not sure how helpful this is for the regular user. Is there any other functionality that you are planning to implement?

**Comment by Rob-Lop** [comment]
> Thank you for your pull request. As far as I can see, this piece of work will only add a text object to the centre of the scene. I am not sure how helpful this is for the regular user, given that this is already visible through the World's custom properties.
> 
> Is there any other functionality that you are planning to implement?

Yes, it only adds a text object but I think this is essential for people working in GIS projects (like me).
Before this patch, the user isn't able to know the real coordinates of the objects.
So, if you want to insert in Blender, GIS data from multiple kind of data source (like shapefile, georeferenced rasted, ascii grid or anything else compatible with the BlenderGIS addon), you must know the recalculated origin of cityjson addon importer. This is essential for georeferenced scene in order to match all the data.
image

But if a user don't care about georeferencing and use cityjson only for an "artist" purpose, yes it's not helpful (that's why i put a checkbox) :)

Yes, I need also to implement the textured cityjson importer. I have already taken a look but it's a hard stuff because I'm not an expert in texturing and UV in Blender and I'm not a specialist about jsoncity file data structure and the way of texture implementation in the json file.

**Comment by liberostelios** [comment]
I see your point. Nevertheless, finding out the origin's real coordinates is already possible via the World's custom properties: 

Screenshot 2020-05-07 at 11 03 51

I doubt that adding them also as a text object in the scene is a better way. Maybe we should implement some kind of GUI that shows those coordinates more prominently. And I guess we should also make it more clear in the documentation that this is possible now.

Regarding textures, please don't hesitate to contact me if you need any further assistance. We are already working on a similar functionality for [ninja](http://ninja.cityjson.org).

**Comment by Rob-Lop** [comment]
Sorry, I missed this feature.
Yes, maybe there is an improvement to integrate in the documentation and the GUI or using the same georeferencing stuff of BlenderGIS addon.

For textures, I think the first step is to understand the data structure for textures in cityjson file.

**Pull request closed without merging**
